name: Deploy Subscription Placement

on:
  workflow_dispatch:  # This makes the workflow trigger manually

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_SECRET_ID }}
  COMPANY_PREFIX: ${{ secrets.COMPANY_PREFIX }}
  LANDING_ZONE_ONLINE_SUBSCRIPTION_ID: ${{ secrets.ONLINE_SUBSCRIPTION_ID }}
  LANDING_ZONE_CORP_SUBSCRIPTION_ID: ${{ secrets.CORP_SUBSCRIPTION_ID }}
  PLAT_CONNECTIVITY_SUBSCRIPTION_ID: ${{ secrets.CONNECTIVITY_SUBSCRIPTION_ID }}
  PLAT_MANAGEMENT_SUBSCRIPTION_ID: ${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner for PowerShell support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Uinstall AzureRm Module
      run: |
        Uninstall-Module -Name Az -Force -ErrorAction SilentlyContinue
      shell: pwsh

    - name: Install Az PowerShell Module
      run: |
        Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser
      shell: pwsh

    - name: Log in to Azure
      run: |
        Connect-AzAccount -ServicePrincipal `
          -TenantId ${{ secrets.AZURE_TENANT_ID }} `
          -SubscriptionId ${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }} `
          -ApplicationId ${{ secrets.AZURE_CLIENT_ID }} `
          -Password ${{ secrets.AZURE_SECRET_ID }}
      shell: pwsh

    - name: Run WhatIf to Validate the Deployment
      id: whatif
      run: |
        $inputObject = @{
            DeploymentName        = -join ('alz-SubscriptionPlacementDeployment-{0}' -f (Get-Date -Format 'yyyyMMddTHHMMssffffZ'))[0..63]
            Location              = 'norwayeast'
            ManagementGroupId     = 'alz'
            TemplateFile          = ".\config\orchestration\subscription\subscriptionPlacement.main.bicep"

            # Pass additional parameters inline
            parCompanyPrefix = '${{ secrets.COMPANY_PREFIX }}'
            parTopLevelManagementGroupPrefix = 'alz'
            parTopLevelManagementGroupDisplayName = 'alz-${{ secrets.COMPANY_PREFIX }}'
            parPlatformMgmtAlzDefaultsEnable = $true
            parLandingZoneMgAlzDefaultsEnable = $true
            parSandboxMgDefaultsEnable = $true
            parDecommissionedMgDefaultsEnable = $true
            parLandingZoneMgConfidentialEnable = $false
            
            # Subscription parameters
            parLandingZoneOnlineSubcriptionId = '${{ secrets.LANDING_ZONE_ONLINE_SUBSCRIPTION_ID }}'
            parLandingZoneCorpSubcriptionId = '${{ secrets.LANDING_ZONE_CORP_SUBSCRIPTION_ID }}'
            parPlatConnectivitySubcriptionId = '${{ secrets.PLAT_CONNECTIVITY_SUBSCRIPTION_ID }}'
            parPlatManagementSubcriptionId = '${{ secrets.PLAT_MANAGEMENT_SUBSCRIPTION_ID }}'
        }

        try {
          # Run WhatIf
          New-AzManagementGroupDeployment @inputObject -WhatIf
        }
        catch {
          Write-Error "WhatIf validation failed. Stopping deployment."
          exit 1  # Exit with an error code to stop the pipeline if WhatIf fails
        }
      shell: pwsh

    - name: Proceed with Actual Deployment if WhatIf Passes
      if: ${{ success() }}  # Only run if the WhatIf step succeeded
      run: |
        $inputObject = @{
            DeploymentName        = -join ('alz-SubscriptionPlacementDeployment-{0}' -f (Get-Date -Format 'yyyyMMddTHHMMssffffZ'))[0..63]
            Location              = 'norwayeast'
            ManagementGroupId     = 'alz'
            TemplateFile          = ".\config\orchestration\subscription\subscriptionPlacement.main.bicep"

            # Pass additional parameters inline
            parCompanyPrefix = '${{ secrets.COMPANY_PREFIX }}'
            parTopLevelManagementGroupPrefix = 'alz'
            parTopLevelManagementGroupDisplayName = 'alz-${{ secrets.COMPANY_PREFIX }}'
            parPlatformMgmtAlzDefaultsEnable = $true
            parLandingZoneMgAlzDefaultsEnable = $true
            parSandboxMgDefaultsEnable = $true
            parDecommissionedMgDefaultsEnable = $true
            parLandingZoneMgConfidentialEnable = $false
            
            # Subscription parameters
            parLandingZoneOnlineSubcriptionId = '${{ secrets.LANDING_ZONE_ONLINE_SUBSCRIPTION_ID }}'
            parLandingZoneCorpSubcriptionId = '${{ secrets.LANDING_ZONE_CORP_SUBSCRIPTION_ID }}'
            parPlatConnectivitySubcriptionId = '${{ secrets.PLAT_CONNECTIVITY_SUBSCRIPTION_ID }}'
            parPlatManagementSubcriptionId = '${{ secrets.PLAT_MANAGEMENT_SUBSCRIPTION_ID }}'
        }

        # Run the actual deployment
        New-AzManagementGroupDeployment @inputObject
      shell: pwsh
