name: Deploy Management Group

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: actions/checkout@v2
    - name: Log in to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_SECRET_ID }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy Bicep Template
      run: |
        az deployment tenant create \
          --template-file ./config/orchestration/managementGroup/managementGroup.main.bicep \
          --location norwayeast \
          --parameters parCompanyPrefix='${{ secrets.COMPANY_PREFIX }}' \
                      parTopLevelManagementGroupPrefix='alz' \
                      parTopLevelManagementGroupDisplayName='alz-${{ secrets.COMPANY_PREFIX }}' \
                      parPlatformMgmtAlzDefaultsEnable=true \
                      parLandingZoneMgAlzDefaultsEnable=true \
                      parSandboxMgDefaultsEnable=true \
                      parDecommissionedMgDefautsEnable=true \
                      parLandingZoneMgConfidentialEnable=false
