name: Deploy Policy Assignments

on:
  workflow_dispatch:  # This makes the workflow trigger manually

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner for Linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure using Azure CLI with Service Principal
      run: |
        echo "Logging into Azure..."
        az login --service-principal \
          -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_SECRET_ID }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
        az account set --subscription ${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}
      shell: bash  # Use Bash shell for Azure CLI commands

    - name: Install Az PowerShell Module
      run: |
        echo "Installing Az PowerShell module..."
        Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser
      shell: pwsh

    - name: Make PowerShell Script Executable
      run: chmod +x ./pipeline-scripts/Deploy-ALZLogging.ps1

    - name: Run PowerShell Script for Deployment
      run: |
        # Run the Deploy-ALZLogging.ps1 script and pass secrets as arguments
        ./pipeline-scripts/Deploy-ALZLogging.ps1 `
          -companyPrefix "${{ secrets.COMPANY_PREFIX }}" `
          -managementSubscriptionId "${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}" `
          -location "${{ secrets.LOCATION }}"
      shell: pwsh
