name: Deploy Subscription Placement

on:
  workflow_run:
    workflows: ["Deploy Management Groups and Policy Definitions"] # Name of the first workflow
    types:
      - completed # Trigger when the first workflow completes

jobs:
  deploy-whatif-subscription-placement:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if the first workflow succeeded
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate to Az CLI using OIDC
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # Run WhatIf to Validate the Deployment
      - name: Run WhatIf for Subscription Placement Deployment
        id: whatif-run-subscription-placement
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ./pipeline-scripts/Deploy-ALZSubscriptionPlacement.ps1 `
              -companyPrefix "${{ secrets.COMPANY_PREFIX }}" `
              -landingZoneOnlineSubcriptionId "${{ secrets.ONLINE_SUBSCRIPTION_ID }}" `
              -landingZoneCorpSubcriptionId "${{ secrets.CORP_SUBSCRIPTION_ID }}" `
              -platConnectivitySubcriptionId "${{ secrets.CONNECTIVITY_SUBSCRIPTION_ID }}" `
              -platManagementSubcriptionId "${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}"
              -location "${{ secrets.LOCATION }}"
              -WhatIf

            echo "$WhatIfOutput" > whatif_subscription_placement.txt
          azPSVersion: "latest"

      # Save WhatIf Output to Environment File for Subscription Placement
      - name: Save WhatIf Output for Subscription Placement
        run: echo "WHATIF_SUBSCRIPTION_PLACEMENT=$(cat whatif_subscription_placement.txt)" >> $GITHUB_ENV

      # Publish WhatIf Output for Subscription Placement
      - name: Publish WhatIf Output for Subscription Placement
        run: echo "${{ env.WHATIF_SUBSCRIPTION_PLACEMENT }}"

  bicep-deploy-subplacesubscription-placementment:
    name: "Bicep Deploy Subscription Placement"
    environment: prod
    needs: [deploy-whatif-subscription-placement]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only runs on main branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate to Az CLI using OIDC
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # Proceed with Actual Deployment if WhatIf Passes
      - name: Run Subscription Placement Deployment
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ./pipeline-scripts/Deploy-ALZSubscriptionPlacement.ps1 `
              -companyPrefix "${{ secrets.COMPANY_PREFIX }}" `
              -landingZoneOnlineSubcriptionId "${{ secrets.ONLINE_SUBSCRIPTION_ID }}" `
              -landingZoneCorpSubcriptionId "${{ secrets.CORP_SUBSCRIPTION_ID }}" `
              -platConnectivitySubcriptionId "${{ secrets.CONNECTIVITY_SUBSCRIPTION_ID }}" `
              -platManagementSubcriptionId "${{ secrets.MANAGEMENT_SUBSCRIPTION_ID }}"
              -location "${{ secrets.LOCATION }}"
          azPSVersion: "latest"
