name: 2 Custom Policy Definitions

on:
    workflow_run:
        workflows: ["1 Management Groups Deployment"]
        types:
            - completed

jobs:
    bicep-whatif-for-policy-definitions:
        name: 'Bicep WhatIf for Policy Definitions'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: 'Az CLI login'
              uses: azure/login@v1
              with:
                  creds: ${{secrets.AZURE_CREDENTIALS}}
                  enable-AzPSSession: true
                  
            - name: Check if Root Management groups exist
              id: whatif-check-management-groups
              uses: azure/powershell@v1
              with:
                inlineScript: |
                    $parTargetManagementGroupId = "alz"
                    
                    $targetManagementGroupExists = Get-AzManagementGroup -GroupName $parTargetManagementGroupId -ErrorAction SilentlyContinue
                    
                    if (-not $targetManagementGroupExists) {
                        throw "Management group '$parTargetManagementGroupId' does not exist"
                    }
                azPSVersion: 'latest'

            - name: Run WhatIf for Policy Definitions Deployment
              id: whatif-run-policy-definitions
              uses: azure/powershell@v1
              with:
                inlineScript: |
                    $WhatIfOutput = ./pipeline-scripts/Deploy-ALZCustomPolicyDefinitions.ps1 `
                        -companyPrefix "${{secrets.COMPANY_PREFIX}}" `
                        -location "${{secrets.LOCATION}}" `
                        -parTargetManagementGroupId "alz" `
                        -WhatIf
                    echo "$WhatIfOutput" > whatif_policy_definitions.txt
                azPSVersion: 'latest'

            - name: Save WhatIf Output to Environment File for Policy Definitions
              run: echo "WHATIF_POLICY_DEFINITIONS=$(cat whatif_policy_definitions.txt)" >> $GITHUB_ENV

            - name: Publish WhatIf Output for Policy Definitions
              run: echo "${{env.WHATIF_POLICY_DEFINITIONS}}"

    bicep-deploy-policy-definitions:
        name: 'Bicep Deploy Policy Definitions'
        environment: prod
        needs: [bicep-whatif-for-policy-definitions]
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'


        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: 'Az CLI login'
              uses: azure/login@v1
              with:
                  creds: ${{secrets.AZURE_CREDENTIALS}}
                  enable-AzPSSession: true

            - name: Deploy Policy Definitions
              uses: azure/powershell@v1
              with:
                  inlineScript: |
                      ./pipeline-scripts/Deploy-ALZCustomPolicyDefinitions.ps1 `
                          -companyPrefix "${{secrets.COMPANY_PREFIX}}" `
                          -location "${{secrets.LOCATION}}" `
                          -parTargetManagementGroupId "alz"
                  azPSVersion: 'latest'
              