name: Reusable WhatIf and Deploy Workflow

on:
  workflow_call:
    inputs:
      whatIf:
        description: 'Run WhatIf before deployment'
        required: true
        type: boolean
      deployManagementGroups:
        description: 'Run deployment for management groups'
        required: true
        type: boolean
      deployPolicyDefinitions:
        description: 'Run deployment for policy definitions'
        required: true
        type: boolean
      environment:
        description: 'The environment where the workflow will be deployed'
        required: true
        type: string

jobs:
  management-groups-whatif:
    if: ${{ inputs.whatIf == true && inputs.deployManagementGroups == true }}  # Boolean comparison
    name: 'WhatIf Management Groups'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run WhatIf for Management Groups
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $WhatIfOutput = ./pipeline-scripts/Deploy-ALZManagementGroups.ps1 `
              -companyPrefix "myCompanyPrefix" `
              -parTopLevelManagementGroupDisplayName "alz-myCompany" `
              -location "eastus" `
              -WhatIf
            echo "$WhatIfOutput" > whatif_management_groups.txt
          azPSVersion: "latest"

      - name: Save WhatIf Output for Management Groups
        run: echo "WHATIF_MANAGEMENT_GROUPS=$(cat whatif_management_groups.txt)" >> $GITHUB_ENV

      - name: Publish WhatIf Output for Management Groups
        run: echo "${{ env.WHATIF_MANAGEMENT_GROUPS }}"

  management-groups-deploy:
    if: ${{ inputs.deployManagementGroups == true }}
    name: 'Deploy Management Groups'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: management-groups-whatif

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Management Groups
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ./pipeline-scripts/Deploy-ALZManagementGroups.ps1 `
              -companyPrefix "myCompanyPrefix" `
              -parTopLevelManagementGroupDisplayName "alz-myCompany" `
              -location "eastus"
          azPSVersion: "latest"
